# Generated by Django 3.1.3 on 2020-11-16 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201116_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['updated']},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['ordering', 'updated']},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='created',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='created',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.board'),
        ),
    ]
